# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='f_author',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='f_message',
        ),
        migrations.AddField(
            model_name='favorite',
            name='quote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='main.Quote'),
            preserve_default=False,
        ),
    ]
